[build]
  command = "npm run compile:contracts && npm run build"
  publish = "build_webpack"

[[redirects]]
  from = "https://solidity-05.ethernaut.openzeppelin.com/*"
  to = "https://ethernaut.openzeppelin.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://ethernaut.zeppelin.solutions/*"
  to = "https://ethernaut.openzeppelin.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://ethernaut-devcon3.zeppelin.solutions/*"
  to = "https://ethernaut.openzeppelin.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://ethernaut-ethuoft.zeppelin.solutions/*"
  to = "https://ethernaut.openzeppelin.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/"
  status = 200