[profile.default]
src             = 'src'                                 # The source directory
out             = 'out'                                 # The output directory
libs            = ['lib']                               # A list of library directories
optimizer       = true                                  # Enable or disable the solc optimizer
optimizer_runs  = 1000                                  # The number of optimizer runs
fs_permissions  = [{ access = "read", path = "./"}]     # Gives permission to read files for compilation objects.
evm_version = "prague"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
